Clean up addpy and addpy2

diff --git a/addpy2 b/addpy2
--- a/addpy2
+++ b/addpy2
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
-[[ -z "${1}" ]] && {
-printf '%s\n' "Error: Type the name of the py2 package you want to add." >&2
-printf '%s\n' "Example: ./addpy2 instagram (adds python2-instagram)" >&2
-exit 1
+
+[[ -n "$1" ]] || {
+    printf '%s\n' 'Error: Type the name of the py2 package you want to add.' >&2
+    printf '%s\n' 'Example: ./addpy2 instagram (adds python2-instagram)' >&2
+    exit 1
 }
 
-echo """
-[python2-${1}]
-url = https://pypi.python.org/pypi/${1}/
-regex = ([0-9\.]*)\.tar\.gz
-""" >> archversion.conf
+printf '\n%s\n%s\n%s\n\n' \
+    "[python2-$1]" \
+    "url = https://pypi.python.org/pypi/$1/" \
+    'regex = ([0-9\.]*)\.tar\.gz' \
+        >> archversion.conf
